# All styling settings for your D324 theme should be entered here

# neal_grace THEME COLORS
# Set theme colors here.  They will automatically be injected into SASS as variables during "npm run dev" or equivalent
# and will be added to other related files such as the Gutenberg theme support yaml file
d324colors:
  body-color:
    name: Theme Body Text Color
    value: "#1E2345"
  body-bg:
    name: Theme Body Background Color
    value: "#FCFCFC"
  link:
    name: Theme Link Color
    value: "#1E2345"
  heading:
    name: Theme Heading Color
    value: "#1E2345"
  primary:
    name: Theme Primary Color
    value: "#1E2345"
  secondary:
    name: Theme Secondary Color
    value: "#C84630"
  accent:
    name: Theme Accent Color
    value: "#FFF5B7"
  alternate-1:
    name: Theme Alternate Color 1
    value: "#160510"
  alternate-2:
    name: Theme Alternate Color 2
    value: "#266666"
  danger:
    name: Theme Danger Color
    value: "#C84630"
  warning:
    name: Theme Warning Color
    value: "#FEC114"
  info:
    name: Theme Info Color
    value: "#17A2B8"
  success:
    name: Theme Success Color
    value: "#28A745"
  dark:
    name: Theme Dark Color
    value: "#160510"
  light:
    name: Theme Light Color
    value: "#E1E1E1"
  black:
    name: Theme Black Color
    value: "#000000"
  white:
    name: Theme White Color
    value: "#FFFFFF"

# neal_grace THEME FONT FAMILIES
# Set theme font family settings here.  They will automatically be injected into SASS as variables during "npm run dev"
# or equivalent and will be added to other related files such as the Gutenberg theme support yaml file
d324fontfamilies:
  font-family-sans-serif:
    name: Theme Sans Serif Font Family Stack
    value: Muli, Corbel, "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", "DejaVu Sans", "Bitstream Vera Sans", "Liberation Sans", Verdana, "Verdana Ref", sans-serif
  font-family-serif:
    name: Theme Serif Font Family Stack
    value: Merriweather, Constantia, "Lucida Bright", Lucidabright, "Lucida Serif", Lucida, "DejaVu Serif", "Bitstream Vera Serif", "Liberation Serif", Georgia, serif
  font-family-monospace:
    name: Theme Monospace Font Family Stack
    value: Consolas, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", Monaco, "Courier New", Courier, monospace
  font-family-base:
    name: Theme Body Font Family Stack
    value: $font-family-sans-serif
  headings-font-family:
    name: Theme Heading Font Family Stack
    value: $font-family-serif

# neal_grace THEME FONT Sizing
# Set theme font family settings here.  They will automatically be injected into SASS as variables during "npm run dev"
# or equivalent and will be added to other related files such as the Gutenberg theme support yaml file
d324themefontsizing:
  body:
    font-size: 1rem
    font-weight: normal
    line-height: 1.875
  headings:
    h1:
      font-size:   42px
      font-weight: 700
      line-height: 1.25
    h2:
      font-size:   38px
      font-weight:  700
      line-height: 1.25
    h3:
      font-size:   32px
      font-weight:  700
      line-height: 1.25
    h4:
      font-size:   26px
      font-weight: 700
      line-height: 1.222222
    h5:
      font-size:   22px
      font-weight: 700
      line-height: 1
    h6:
      font-size:   18px
      font-weight: 700
      line-height: 1

# neal_grace THEME LAYOUT
# Set theme layout settings here to be included in variables.scss for the compiler
d324layout:
  grid-gutter-width:
    name: Theme Grid Gutter Width
    value: 1.875rem

# neal_grace BOOTSTRAP OPTIONS
# Set Bootstrap SASS options to be included in _variables.scss for the compiler
d324bootstrapoptions:
  enable-caret:
    name: Theme Bootstrap Option - Enable Caret
    value: true
  enable-rounded:
    name: Theme Bootstrap Option - Enable Rounded
    value: true
  enable-shadows:
    name: Theme Bootstrap Option - Enable Shadows
    value: false
  enable-gradients:
    name: Theme Bootstrap Option - Enable Gradients
    value: false
  enable-transitions:
    name: Theme Bootstrap Option - Enable Transitions
    value: true
  enable-prefers-reduced-motion-media-query:
    name: Theme Bootstrap Option - Enable Reduced Motion
    value: true
  enable-grid-classes:
    name: Theme Bootstrap Option - Enable Grid Classes
    value: true
  enable-pointer-cursor-for-buttons:
    name: Theme Bootstrap Option - Enable Pointer Cursor
    value: true
  enable-print-styles:
    name: Theme Bootstrap Option - Enable Print Styles
    value: true
  enable-responsive-font-sizes:
    name: Theme Bootstrap Option - Enable Responsive Font Sizes
    value: true
  enable-validation-icons:
    name: Theme Bootstrap Option - Enable Validation Icons
    value: true
  enable-deprecation-messages:
    name: Theme Bootstrap Option - Enable Deprecation Messages
    value: true

# neal_grace THEME UTILITY OPTIONS
d324utilityoptions:
  browsersync-proxy-url:
    name: URL Browsersync will redirect to when loaded in watch mode
    value: "http://d324.local"
